### ISSUE TITLE
Error inflating class

### ISSUE THREAD

**Issue by nikolaykuz** [dmitry-zaitsev/CircleLayout#2]
I am newbie of Android. I have completed this lesson
http://developer.android.com/training/basics/firstapp/index.html

and trying to change layout to the circle one. Maybe I am missing something trivial.

I have imported the source to Eclipse, set the CircleLayout project as library and specified that as referenced library in MyProject.
http://developer.android.com/tools/projects/projects-eclipse.html#ReferencingLibraryProject

In AndroidManifest.xml I have added

``` xml
<activity
     android:name="ru.biovamp.widget.CircleLayout">
</activity>
```

activity_main.xml

``` xml
<?xml version="1.0" encoding="utf-8"?>
<ru.biovamp.widget.CircleLayout
      xmlns:android="http://schemas.android.com/apk/res/android"
      xmlns:tools="http://schemas.android.com/tools"
      xmlns:app="http://schemas.android.com/apk/res/org/myproject/client/android"
      android:layout_width="match_parent"
      android:layout_height="match_parent"
      android:background="@android:color/white"
      >

    <!-- app:angleOffset="90.0" -->

    <EditText android:id="@+id/edit_message"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:hint="@string/edit_message" />

</ru.biovamp.widget.CircleLayout>
```

from logcat

``` xml
02-26 21:04:11.060: E/AndroidRuntime(608): FATAL EXCEPTION: main
02-26 21:04:11.060: E/AndroidRuntime(608): java.lang.RuntimeException: Unable to start activity ComponentInfo{org.myproject.client.android/org.myproject.client.android.MainActivity}: android.view.InflateException: Binary XML file line #2: Error inflating class ru.biovamp.widget.CircleLayout
02-26 21:04:11.060: E/AndroidRuntime(608):  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1955)
02-26 21:04:11.060: E/AndroidRuntime(608):  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1980)
02-26 21:04:11.060: E/AndroidRuntime(608):  at android.app.ActivityThread.access$600(ActivityThread.java:122)
02-26 21:04:11.060: E/AndroidRuntime(608):  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1146)
02-26 21:04:11.060: E/AndroidRuntime(608):  at android.os.Handler.dispatchMessage(Handler.java:99)
02-26 21:04:11.060: E/AndroidRuntime(608):  at android.os.Looper.loop(Looper.java:137)
02-26 21:04:11.060: E/AndroidRuntime(608):  at android.app.ActivityThread.main(ActivityThread.java:4340)
02-26 21:04:11.060: E/AndroidRuntime(608):  at java.lang.reflect.Method.invokeNative(Native Method)
02-26 21:04:11.060: E/AndroidRuntime(608):  at java.lang.reflect.Method.invoke(Method.java:511)
02-26 21:04:11.060: E/AndroidRuntime(608):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
02-26 21:04:11.060: E/AndroidRuntime(608):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
02-26 21:04:11.060: E/AndroidRuntime(608):  at dalvik.system.NativeStart.main(Native Method)
02-26 21:04:11.060: E/AndroidRuntime(608): Caused by: android.view.InflateException: Binary XML file line #2: Error inflating class ru.biovamp.widget.CircleLayout
02-26 21:04:11.060: E/AndroidRuntime(608):  at android.view.LayoutInflater.createView(LayoutInflater.java:606)
02-26 21:04:11.060: E/AndroidRuntime(608):  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:680)
02-26 21:04:11.060: E/AndroidRuntime(608):  at android.view.LayoutInflater.inflate(LayoutInflater.java:466)
02-26 21:04:11.060: E/AndroidRuntime(608):  at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
02-26 21:04:11.060: E/AndroidRuntime(608):  at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
02-26 21:04:11.060: E/AndroidRuntime(608):  at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:251)
02-26 21:04:11.060: E/AndroidRuntime(608):  at android.app.Activity.setContentView(Activity.java:1835)
02-26 21:04:11.060: E/AndroidRuntime(608):  at org.myproject.client.android.MainActivity.onCreate(MainActivity.java:16)
02-26 21:04:11.060: E/AndroidRuntime(608):  at android.app.Activity.performCreate(Activity.java:4465)
02-26 21:04:11.060: E/AndroidRuntime(608):  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1049)
02-26 21:04:11.060: E/AndroidRuntime(608):  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1919)
02-26 21:04:11.060: E/AndroidRuntime(608):  ... 11 more
02-26 21:04:11.060: E/AndroidRuntime(608): Caused by: java.lang.reflect.InvocationTargetException
02-26 21:04:11.060: E/AndroidRuntime(608):  at java.lang.reflect.Constructor.constructNative(Native Method)
02-26 21:04:11.060: E/AndroidRuntime(608):  at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
02-26 21:04:11.060: E/AndroidRuntime(608):  at android.view.LayoutInflater.createView(LayoutInflater.java:586)
02-26 21:04:11.060: E/AndroidRuntime(608):  ... 21 more
02-26 21:04:11.060: E/AndroidRuntime(608): Caused by: java.lang.NoClassDefFoundError: ru.biovamp.widget.R$styleable
02-26 21:04:11.060: E/AndroidRuntime(608):  at ru.biovamp.widget.CircleLayout.<init>(CircleLayout.java:87)
02-26 21:04:11.060: E/AndroidRuntime(608):  ... 24 more
02-26 21:09:11.244: I/Process(608): Sending signal. PID: 608 SIG: 9
```

**Comment by nikolaykuz** [comment]
Why do you close without any comment? I am doing something wrong?

**Comment by dmitry-zaitsev** [comment]
First of all - when you creating issue make sure that you set who will be responsible for it.

About your issue - there is a problem with your manifest, not with CircleLayout. You provided wrong Activity name.

**Comment by nikolaykuz** [comment]
First of all, who else can be responsible?

How about you providing a simple compilable project to illustrate CircleLayout working well?

Anyway, I think that silently closing is not polite.

**Comment by dmitry-zaitsev** [comment]
Main contributor should be responsible (me). You didn't even specify that, so I didn't received notification about this issue.

I'll provide sample project, however you still need to read a lot about Android SDK. Otherwise - it's a bit selfish to ask personal help when there is A LOT of documentation. Once again - your problem is in Android basics, not in this library.

**Comment by nikolaykuz** [comment]
> You didn't even specify that, so I didn't received notification about this issue.

Okay, sorry about that.

> however you still need to read a lot about Android SDK

Yes, I know this.

> I'll provide sample project

Very good! Thanks a lot.

**Comment by nikolaykuz** [comment]
How it is going with publishing compilable usage case for this project?

**Comment by dmitry-zaitsev** [comment]
It's ready. Check out an /example/ folder
